- tt_llk_blackhole/llk_lib/llk_unpack_AB_matmul.h
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/18250)
Some of the changes introduced in [this PR](https://github.com/tenstorrent/tt-metal/pull/17723) have caused a hang on Resnet50 BH tests.
Changes introduced by this PR have been reverted.
> #18250: Reverting changes from CFGSHIFTMASK PR

- tt_llk_blackhole/common/inc/ckernel.h
Due to a HW bug in CSR writes, we need to guard them by first disabling branch prediction, and then re-enabling it. This is a workaround for https://github.com/tenstorrent/tt-metal/issues/18064#issuecomment-2685621251 and is proposed as a fix by the HW team.
> #18064: Guard CSRRS by disabling branch prediction

- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fill_dest.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
As we set up new test infrastructure, we've encountered several tests that are currently failing. This PR disables these failing tests so that test runs only include those that are known to be correct and passing.
Running incomplete or misconfigured failing tests can create unnecessary confusion, especially for developers making unrelated changes. They might mistakenly believe their modifications introduced new failures, making debugging more difficult. By disabling these tests, we ensure that test failures are meaningful and actionable.
Once the new test infrastructure is fully set up, we should revisit these disabled tests and re-enable them after proper fixes or updates.
Future work may involve categorizing or marking these tests separately for better tracking.
> fix: disable failing python tests

- tt_llk_blackhole/common/inc/cunpack_common.h
- tt_llk_blackhole/llk_lib/llk_unpack_A.h
- tt_llk_wormhole_b0/common/inc/cunpack_common.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_A.h
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/13953)
`-0.0` Incorrectly handled as `0.0` in `ttnn.signbit`. bfloat16 data format should preserve `-0.0` values through the unpacker, math, packer pipeline. However, `-0.0` in bfloat16 format gets passed into the kernel as `0.0` and `signbit` reads this as a positive value.
The detailed reasoning is as follows. When unpacking to the Dest register, bfloat16 values are first packed into Src registers and then moved to Dest. When moving these values from Src, `-0.0` is interpreted as `0.0` and src zero flags are set. This leads to `-0.0` values not being moved, but instead, zeroes being written into relevant locations in Dest. 
Disabled src zero flags for eltwise unary/sfpu operations. `-0.0` values are now moved to Dest …
> #13953: Incorrectly handled bfloat16 -0.0 in ttnn.signbit

- tt_llk_wormhole_b0/common/inc/cunpack_common.h
General rule is:
TT_* type of instruction is used when not all arguments are known at compile time.
TTI_* type of instruction is used when all argument are compile time constants.
Former is slower and more general, latter results in more optimal and faster code.
Note: Could be that using non const (non constexpr) variable in TTI_* type of instruction works in cases when compiler deduces that some variable depends only on compile time known values. But, this is unsafe to rely on.
> Fix: Use TT_* instruction type instead of TTI_* as the parameter is not compile time known

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_recip.h
Div OP, which uses reciprocal underneath, produces unexpected numbers on Blackhole in specific situations.
Issue and fix reported in https://github.com/tenstorrent/tt-metal/issues/18496.
Investigation and fix provided by @umadevimcw in the original issue.
> [Blackhole] Fix undefined numbers appearing in div SFPU OP

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_add_int32.h
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_sub_int32.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_add_int32.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_sub_int32.h
I don't have access to any documentation for this instruction, but from my own testing I don't think two cycles are used.  Probably confusion with SFPMAD?
> SFPIADD doesn't take two cycles.

- tt_llk_blackhole/llk_lib/llk_unpack_AB_matmul.h
[StableDiffusion](https://github.com/tenstorrent/tt-metal/issues/18988)
[Whisper BH](https://github.com/tenstorrent/tt-metal/issues/19038#event-16725147898)
[Resnet50 hang](https://github.com/tenstorrent/tt-metal/issues/18812#issuecomment-2714656185) needs to be reopened.
Reverting changes as it is correlated to issues in at least 2 models.
This reverts commit f2e18882491f6c86a7706f008d94608007a60533.
> Revert "Readding CFGSHIFTMASK changes to unpack AB matmul (#34)"

- tt_llk_blackhole/common/inc/ckernel.h
[tt-metal#16439](https://github.com/tenstorrent/tt-metal/issues/16439)
[tt-metal#18550](https://github.com/tenstorrent/tt-metal/issues/18550)
Hangs are present in ResNet 50 and Stable Diffusion 1.4. These issues are blocking further model bringup work. The hangs are reproducible with matmul tests, namely `test_benchmark.py` and `test_benchmark.cpp`. 
We are disabling instruction coalescing in Blackhole inside `load_replay_buf` calls. This will unblock RN and SD work.
> #16439: Disable instruction coalescing feature

- .pre-commit-config.yaml
- tests/python_tests/helpers/format_config.py
- tests/python_tests/helpers/pack.py
- tests/python_tests/helpers/param_config.py
- tests/python_tests/helpers/test_config.py
- tests/python_tests/test_eltwise_unary_datacopy.py
Thus far, we've had some unused imports in our Python code
This change should automate removal of unused imports from our code.
> build: remove unused python imports using autoflake

- tests/helpers/src/brisc.cpp
- tests/helpers/src/trisc.cpp
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/sources/tilize_calculate_untilize_L1.cpp
Once TRISCs were synced to run at the same time in order to resolve hangs because unpack was lagging behind pack and math TRISCs, `test_tilize_calculate_utilize.py` started to fail because it attempted to fuse two LLK pipeline runs. This means that in the first run we unpack from two buffers in L1 and after math we pack to two other buffers in L1. Then in the second run we unpack from these two buffers that pack wrote to, however `unpacker` started to read from the buffers before the `packer` completed writing to L1. 
This worked previously because the `unpacker` was severely lagging behind `packer` and `math` (approximately 700 cycles), and this lag allowed for `packer` to finish writing to L1 before the `unpacker` would start reading. Since `unpacker` is synced with `packer` we must …
> [Test Infrastructure] Fixed bug in test_tilize_calculate_untilize_L1 

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_recip.h
https://github.com/tenstorrent/tt-metal/issues/19766
Reciprocal operation in Blackhole doesn't have support for `is_fp32_dest_acc_en`, which causes precision difference compared to WH and BH output.
This PR introduced the missing template parameter. tt-metal counterpart of this change can be found [here](https://github.com/tenstorrent/tt-metal/compare/main...refs/heads/fvranicTT/add-dest-acc-config-to-reciprocal).
> fix: add parameter for configuring dest accumulation

- .gitignore
- tests/python_tests/helpers/__init__.py
- tests/python_tests/helpers/device.py
- tests/python_tests/helpers/format_arg_mapping.py
- tests/python_tests/pytest.ini
- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fill_dest.py
- tests/python_tests/test_matmul.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_pack_untilize.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/python_tests/test_unpack_tilize.py
- tests/python_tests/test_unpack_untilize.py
Previously, we were reading from L1 before verifying if our Tensix operations completed. This could have resulted in reading invalid data from L1, leading to misinterpretation of test failures as functional issues, when in fact the problem might have been a synchronization issue or a hang.
To address this, we’ve updated the flow to ensure that TRISC calls are fully completed before we read the results from L1. Additionally, we replaced our assertion calls with wait calls that pause execution until the Tensix operation finishes. This change improves our ability to distinguish between actual test failures (due to incorrect results) and potential hangs, as the test will now wait for the operation to complete instead of failing immediately on an assertion, which previously didn’t provide …
> [Test Infra] Ensure Tensix Operations Complete Before Reading Results from L1 & Wait for Tensix Completion to Expose Hangs

- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fill_dest.py
- tests/python_tests/test_matmul.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_pack_untilize.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/python_tests/test_unpack_tilize.py
- tests/python_tests/test_unpack_untilize.py
None
There are superfluous make clean calls after execution of every test. These aren't needed and present a leftover from debugging.
This PR removes them.
> fix: remove superfluous make clean calls

- .github/Dockerfile.ird
None
There's compile issue when building tt-metal using our tt-llk IRD image:
```
In file included from /localdev/fvranic/tt-metal/tt_metal/common/metal_soc_descriptor.cpp:5:
In file included from /localdev/fvranic/tt-metal/tt_metal/api/tt-metalium/metal_soc_descriptor.h:14:
In file included from /localdev/fvranic/tt-metal/tt_metal/third_party/umd/device/api/umd/device/tt_cluster_descriptor.h:19:
In file included from /localdev/fvranic/tt-metal/tt_metal/third_party/umd/device/api/umd/device/chip/chip.h:9:
/localdev/fvranic/tt-metal/tt_metal/third_party/umd/device/api/umd/device/lock_manager.h:8:10: fatal error: 'boost/interprocess/sync/named_mutex.hpp' file not found
8 | #include <boost/interprocess/sync/named_mutex.hpp>
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error …
```
> build: switch IRD base image to metaillium-dev

- tt_llk_blackhole/llk_lib/llk_unpack_tilize.h
- tt_llk_wormhole_b0/common/inc/cmath_common.h
- tt_llk_wormhole_b0/common/inc/cpack_common.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_tilize.h
[#16860](https://github.com/tenstorrent/tt-metal/issues/16860)
Int32/UInt32 tilize support was missing on both WH and BH.
In order to tilize 32-bit inputs without losing accuracy, the data cannot be unpacked to Source A/Source B registers - the provided solution unpacks tilized 32-bit integers directly into the destination register.
> LLK tilize support for Int32/UInt32 inputs

- tests/python_tests/helpers/__init__.py
- tests/python_tests/helpers/device.py
- tests/python_tests/helpers/format_arg_mapping.py
- tests/python_tests/helpers/format_config.py
- tests/python_tests/helpers/param_config.py
- tests/python_tests/helpers/unpack.py
- tests/python_tests/helpers/utils.py
- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fill_dest.py
- tests/python_tests/test_matmul.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_pack_untilize.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/python_tests/test_unpack_tilize.py
- tests/python_tests/test_unpack_untilize.py
Instead of reading words from device to extract our result vector, we instead call read_from_device which reads the data in bytes. Previously this was set to read a fixed number or words and then a fixed number of bytes (maximum amount of bytes because it was set to read bytes for 32bit datums). 
However, we want to be able to be flexible with our stimuli generation for testing, which means input tensors will be of different sizes and different formats, thus the number of bytes we read should be flexible to these changes, instead of fixed. 
Now we read the exact number of bytes necessary, we take into account the size of our output vector and the size of our datum, defined by `format_num_bytes` map. This calculation is done in `utils.py::calculate_read_byte_count` and the result is passed …
> [Test Infra] Added flexibility for dynamic byte count calculation for reading datums of different sizes

- tt_llk_blackhole/llk_lib/llk_math_eltwise_binary.h
- tt_llk_blackhole/llk_lib/llk_math_reduce.h
- tt_llk_wormhole_b0/llk_lib/llk_defs.h
- tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_binary.h
- tt_llk_wormhole_b0/llk_lib/llk_math_reduce.h
[Link to Github Issue](https://github.com/tenstorrent/tt-metal/issues/20023)
Binary broadcast cols and reduce w (row) kernels lack support for 16x32 tiny tiles, which can speed up SDPA decode OP.
Added support for those two OPs to work on 16x32 tiles, and added unit testing for those cases.
> Add missing tiny tiles support to bcast col and reduce w

- tests/Makefile
- tests/helpers/ld/sections.ld
We plan to change the target triple from `riscv32-unknown-elf` to `riscv32-tt-elf`, to reduce the possibility of confusion between riscv toolchains. This changes the Makefile so that it doesn't care what the manufacturer component is.
I notice that a linker script was incorrectly adding `/opt/riscv32i/riscv32-unknown-elf/lib` as a library search path. It should not be looking there.
> Be agnostic about target triple's manufacturer

- tt_llk_blackhole/common/inc/cpack_common.h
- tt_llk_wormhole_b0/common/inc/cpack_common.h
https://github.com/tenstorrent/tt-metal/issues/18914
UInt8 packing is not correctly supported when DEST reg is in 16 bit operating mode, only 32 bit mode. This is because in BBE there was an assumption to always have 32 bit mode enabled for int formats.
Change the programming of PCK_DEST_RD_CTRL config regs based on 32 vs 16 bit Dest for (u)int8.
> Fix PCK_DEST_RD_CTRL config based on 32 vs 16 bit Dest for int8

- .github/workflows/tt-metal-integration-tests.yml
None
After some changes landed in tt-metal (https://github.com/tenstorrent/tt-metal/pull/21035), our tt-metal integration tests workflow got broken. This change should fix it.
A few days ago a change was introduced that requires fetching latest tags. Our pipeline wasn’t set up for that.
> build: use latest tt-metal ci image for running integration tests

- tt_llk_blackhole/common/inc/ckernel_globals.h
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_topk.h
- tt_llk_wormhole_b0/common/inc/ckernel_globals.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_topk.h
tenstorrent/tt-metal#21301
`topk_replay_init` shouldn't be exposed to LLK users.  This change makes it internal to the LLK.
For both Wormhole and Blackhole:
- Removed `topk_replay_init` `extern` declaration.
- Added `static int32_t topk_replay_init = 0;`
- Added `topk_replay_init = 0` to `_init_topk`.
> Make topk_replay_init internal to LLK.

- .github/workflows/tt-metal-integration-tests.yml
None
Using `latest` tag should make our pipeline keep track of the changes in tt-metal docker setup. It could prove to be counterproductive if we start observing failures due to changes that aren’t under our control, but let’s give it a shot.
Image hash of the metal CI docker image is now set to use `latest` tag.
> build: use `latest` tag for metal CI docker image

- tests/helpers/include/data_format_inference.h
- tests/helpers/include/params.h
- tests/sources/eltwise_unary_datacopy_test.cpp
- tests/sources/eltwise_unary_sfpu_test.cpp
- tests/sources/fill_dest_test.cpp
- tests/sources/matmul_test.cpp
- tests/sources/multiple_tiles_eltwise_test.cpp
- tests/sources/pack_untilize_test.cpp
- tests/sources/reduce_test.cpp
- tests/sources/sfpu_binary_test.cpp
- tests/sources/tilize_calculate_untilize_L1.cpp
- tests/sources/unpack_tilize_test.cpp
- tests/sources/unpack_untilize_test.cpp
https://github.com/tenstorrent/tt-llk/issues/80
Tests support Input and Output format parametrization meaning that the user can define the format they what their input tensor in L1 to be and the format of their output in L1. However for the LLK pipeline to run we need to define the intermediary formats including unpacker formats, fpu formats and packer formats. This the user does not define and is left up to us to define according to the best combination which was developed during the format sweep effort. 
The inference model looks at the input and output format defined by client, and dest accumulation, if it is on or off and sets the unpacker and packer src and dest formats accordingly. When dest accumulation is off the packer accepts the format seen in the dst register and then convert …
> [Test Infrastructure] Data format Inference Model 

- .github/workflows/setup-and-test.yml
- .github/workflows/tt-metal-integration-tests.yml
None
This change removes docker container after running.
We used to have this setting in the previous version of metal integration tests workflow, but I mistakenly dropped after the last change. This is now causing issues with PRs coming from forks.
> ci: remove docker container after each run

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_topk.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_topk.h
#102
SFPSWAP doesn't need to be followed by SFPNOP, even on Wormhole.
SFPNOPs removed from topk LLK, and replay buffers adjusted accordingly.
> Remove extraneous SFPSWAP NOPs.

- .github/workflows/setup-and-test.yml
None
Tests take over 20 minutes to finish. This could, in part, be due to very verbose prints of pytests.
This change should reduce verbosity level of tests in the pipeline runs.
> ci: reduce verbosity of pytests

- tt_llk_blackhole/common/inc/ckernel.h
https://github.com/tenstorrent/tt-metal/issues/19201
Although harmless to our knowledge, for easier debugging we want to comment out the redundant calls to disable_gathering as they are disabled at start. 
Commented out calls to disable_gathering
> Comment out calls to disable_gathering

- .pre-commit-config.yaml
- tests/setup_testing_env.sh
None
Currently, we are experiencing [random failures](https://github.com/tenstorrent/tt-llk/actions/runs/14880439156/job/41787137193?pr=169) caused by network issues when downloading the SFPI compiler. However, the error is misleading as it only appears during the pytest execution step. Instead, the failure should occur earlier, during the step where the SFPI compiler is being downloaded.
With this change, GH pipeline should stop if it fails to fetch the compiler or to unpack it. Pytests shouldn't even run.
> chore: update setup_testing_env.sh to display info in case of error

- .github/workflows/on-pr.yml
- .github/workflows/pre-commit.yml
- .github/workflows/setup-and-test.yml
None
Currently, both Blackhole and Wormhole tests are being run regardless of the changes introduced in the PR. Since we only have a limited number of WH runners and just one BH runner available, optimizing resource usage is crucial.
With this change, the CI pipeline will only run the appropriate tests. For example:
- If Wormhole-specific code is changed, tests will only run on the Wormhole runner.
- If Blackhole-specific code is changed, tests will only run on the Blackhole runner.
- If unrelated files (e.g., README) are changed, unit tests will not run, as they are not expected to fail.
This ensures efficient use of resources.
> ci: run LLK test infra conditionally, depending on the changed files

- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_binary.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_exp.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_gelu.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_recip.h
#154
The original implementation used a poor initial guess, which led to high ULPs (~24749) even when using 3 iterations.
The improved initial guess uses one additional FMA.  The maximum error is now approximately 1 ULPs (not checked exactly) for 3 iterations, and 201 ULPs for 2 iterations (used in "approximation mode").
The code was also simplified to reduce operation count.
> Improve reciprocal precision.

- .pre-commit-config.yaml
- tests/python_tests/conftest.py
- tests/python_tests/helpers/__init__.py
- tests/python_tests/helpers/chip_architecture.py
- tests/python_tests/helpers/device.py
- tests/python_tests/helpers/hardware_controller.py
- tests/python_tests/helpers/log_utils.py
- tests/python_tests/helpers/param_config.py
- tests/python_tests/helpers/utils.py
- tests/python_tests/pytest.ini
- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fill_dest.py
- tests/python_tests/test_matmul.py
- tests/python_tests/test_matmul_pack_untilize.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_pack_untilize.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/python_tests/test_unpack_tilize.py
- tests/python_tests/test_unpack_untilize.py
We've come across issues due to using globbing operator for utility imports. This was a relic of the original implementation that had to be tackled at one point in time.
1.  **Removed imports using globbing**
Globbing (from module import *) is bad because it hides dependencies, pollutes the namespace, and increases the risk of circular imports. 
2.  **Skip Decorators:**
Introduced `@skip_for_wormhole` and `@skip_for_blackhole` decorators.
These decorators dynamically check the CHIP_ARCH environment variable to skip tests incompatible with specific architectures. If you want to skip a certain test for a specific architecture, just decorate it with e.g. `@skip_for_wormhole`
3. **Introduced ChipArchitecture enum**
Introduced `ChipArchitecture` enum so we could stop using string comparison …
> feat: stop using globbing when importing utility methods

- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_binary.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_exp.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_gelu.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_recip.h
None
We have to revert #155, because it's causing issues in tt-metal's ttnn tests. The tests seem off, but this needs to be investigated further, and we're blocked by this commit. So, we will revisit this change after some high priority changes land into metal.
This reverts commit 0c54f3b13e4533bb6a666dba748e698404ab52e7.
> fix: revert "Improve reciprocal precision. (#155)"

- tt_llk_blackhole/common/inc/cmath_common.h
- tt_llk_blackhole/llk_lib/llk_math_matmul.h
- tt_llk_wormhole_b0/common/inc/cmath_common.h
- tt_llk_wormhole_b0/llk_lib/llk_math_matmul.h
Power draw during matmul workload can be lowered by adding NOPs into the llk. Here we have enabled the throttling of MM workloads by this method, to various degrees.
This feature can be enabled by setting env variable `TT_MM_THROTTLE_PERF=1, 2, 3, 4, 5`.
Value of 1 produces 73% intensity MM, 2 produces 67% intensity MM, 3 produces 50% intensity MM, 4 produces 40% intensity MM, 5 produces 33% intensity MM.
This currently only works for full tile MM (32x32), but should work for all math fidelities.
> Throttle MM Perf

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_binary_bitwise.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_binary_bitwise.h
NA
Only int32 dtype supported
Expose the dtype param as a template parameter
> Add DataType instruction modifier template for bitwise ops

- tt_llk_blackhole/llk_lib/llk_unpack_common.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_common.h
https://github.com/tenstorrent/tt-metal/issues/19201
The unpacker in _llk_unpack_get_tile function used to do mailbox_writes and then post (increment) a semaphore. It is possible for math and pack thread to read the mailboxes and try to get (decrement) a semaphore which is already zero, thus dropping the decrements. Then later on in _llk_unpack_release_tile the unpacker would wait for the semaphore to be zero, but since the decrements were dropped it would get stuck.
The order of doing the mailbox write and semaphore post has been changed, so the packer and math thread would only try to decrement the semaphore after the sempahore post since that happens before the mailbox write now which will happen before packer and math thread can decrement since their execution is depedent on the …
> Fix ordering of mailbox_write and semaphore_post in unpack_get_tile

- tests/Makefile
None
This PR removes initial implementation for fetching the hardware-specific files from tt-metal. A different approach was taken, to fetch the files before starting pytest session. Makefile approach caused our runtime to double, which wasn't acceptable.
Deleted stale unused code
> chore: cleanup stale code

- .github/scripts/install-exalens.sh
None
After latest FW update for BH, according to the Debug team, we would face issues running our test infra or IRD machines if we don't update exalens version. This shouldn't affect CI runner, but we'll update all the Docker images anyway.
New exalens version containing fixes for UMD.
> build: update version of exalens

- .github/workflows/on-pr.yml
None
Until recently, we only had one available BH runner, which meant we had to execute all of our tests sequentially. In contrast, we had access to Wormhole runners and recently began running tests in parallel by splitting them into five groups, with each group executing on a separate runner.
As of a few days ago, Blackhole runners became available in the shared pool, so we can now leverage them as well.
Just for comparison, BH tests currently take around 30 minutes to finish, while WH take ~8min (5 groups taking around ~7-8 minutes each, running concurrently). This is a significant speedup.
This PR switches BH tests to run on the runners from the org pool. Instead of 1 group of tests, we now divide them into 5 groups to parallelize them.
> ci: switch to blackhole runners from pool

- tt_llk_blackhole/llk_lib/llk_unpack_common.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_common.h
https://github.com/tenstorrent/tt-metal/issues/19201
The llk_unpack_get_tile is still prone to memory reording where the mailbox write can get executed before the semaphore post, leading to the race condition discussed in the issue. 
Modified the code to introduce reads and pseudo usage after store and load respectively, so the former get completed and eventually mailbox write happens after semaphore post.
> Introduced strict ordering in unpack_get_tile

- tt_llk_wormhole_b0/llk_lib/llk_defs.h
- tt_llk_wormhole_b0/llk_lib/llk_math_transpose_dest.h
As suggested by @corsix, this performs a transpose on a 16x16 face of 32-bit values by splitting into two faces of 16-bit values (the low 16 bits and high 16 bits), transposing each face separately using `TRNSPSRCB`, and then recombining into 32-bit values.
A neat way to achieve this (also suggested by @corsix!) is to use the `dest_32b_lo` instruction mode flag on `MOVD2B`/`MOVB2D`.  This allows the low bits to be copied to SrcB, transposed, and copied back.  Followed by the same operation on the high bits.
Further optimisation would involve using the full 32 slots in the replay buffer, rather than overwriting slots 16 to 32 as I'm doing currently.
This was just the most straightforward way to get a working proof of concept.
#134
32-bit types aren't supported by transpose_dest.
See above.
> Add support for 32-bit types to _llk_math_transpose_dest_.

- tt_llk_wormhole_b0/llk_lib/llk_unpack_tilize.h
Unpack to DEST with tilize implementation that is used for INT32 format only works with 1 config context.
Most of other kernel implementations use 2 config contexts.
Due to this it can happen that another kernel left the pointer to config context 1 when unpack to dest with tilize executes, leading to wrong config used.
This change ensures unpack to dest with tilize for int32 format resets config context id to 0, before executing.
> Reset config context to 0 when doing unpack tilize to dest

- tests/python_tests/test_matmul.py
- tests/python_tests/test_matmul_pack_untilize.py
None
It turns out we missed to pass formats to stimuli generator.
> fix: pass format to generate_stimuli in matmul tests

- tests/requirements.txt
None
pytest-split and pytest-randomly seem to not work well together. If a group fails and gets rerun, randomly plugin will randomize tests again and skip running failing tests.
Removed pytest-randomly
> fix: remove pytest-randomly

- tt_llk_blackhole/common/inc/ckernel_sfpu.h
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_rounding_ops.h
- tt_llk_wormhole_b0/common/inc/ckernel_sfpu.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_rounding_ops.h
https://github.com/tenstorrent/tt-metal/issues/22131
Rounding op LLKs are spilled across multiple headers, need to combine it into common header and port to LLK side
Move implementation to LLK repo
> Add rounding ops to LLK

- tt_llk_blackhole/llk_lib/llk_unpack_tilize.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_tilize.h
https://github.com/orgs/tenstorrent/projects/123/views/1?pane=issue&itemId=111603646&issue=tenstorrent%7Ctt-llk%7C220
When writing tests that incorporate unpack_tilize with other unpacker kernels, we need to uninit the unpack_tilize_init otherwise we cannot properly initialize a different unpack kernel and the tests fail. This uninit function is defined and called in metal, but we need one for llk.
> Added unpack_tilize_uninit to llk lib

- .pre-commit-config.yaml
- tests/python_tests/conftest.py
- tests/python_tests/helpers/format_arg_mapping.py
- tests/python_tests/helpers/stimuli_generator.py
- tests/python_tests/helpers/test_config.py
- tests/python_tests/helpers/tilize_untilize.py
- tests/python_tests/helpers/unpack.py
- tests/python_tests/pyproject.toml
- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fill_dest.py
- tests/python_tests/test_matmul.py
- tests/python_tests/test_matmul_pack_untilize.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_pack_untilize.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/python_tests/test_unpack_tilize.py
- tests/python_tests/test_unpack_untilize.py
None
Sort imports using isort.
The way we sort imports that were previously unsorted.
> build: sort python imports automatically

- tt_llk_blackhole/common/inc/ckernel.h
tt_metal will introduce a runtime option to enable gathering.  Whether these functions are called will be controlled on compile option in jit build.
https://github.com/tenstorrent/tt-metal/issues/22240
Gathering is now globally disabled, and load_replay_buf no longer toggles gathering when executing TTI_REPLAY load command.
Have the behavior controlled under the compile option `ENABLE_GATHERING` which will be provided by jit build.
https://github.com/tenstorrent/tt-metal/pull/22424 tracks the tt_metal change for this compile option.
> Conditionally call disable/enable_gathering based on compile option.

- tests/python_tests/test_matmul_unpack_tilize.py
- tests/sources/matmul_unpack_tilize_test.cpp
- tt_llk_blackhole/llk_lib/llk_unpack_tilize.h
https://github.com/orgs/tenstorrent/projects/123?pane=issue&itemId=109488923&issue=tenstorrent%7Ctt-llk%7C173
Adding Matmul test coverage by testing matmul with unpack_tilize. This test cannot fuse this in one llk pipeline. We must first unpack tilize the input tensors and then pack them into L1 and unpack them again to run a matmul on them. 
Needed to incorporate synchronization with `t6_semaphore`, as well as reconfiguring data formats for the next unpack, math and pack kernels in the case that we want to alter our formats when we execute the matmul in the second llk pipeline run. In packer code block, reconfiguring the data formats also sets packer strides.
- In this specific case in the first pipeline run we set the packer strides to pack in tilized format, but in the second run we …
> [Test Infra] Added test to fuse matmul with unpack tilize

- tests/python_tests/conftest.py
- tests/setup_external_testing_env.sh
https://github.com/tenstorrent/tt-llk/issues/224
There was a regression in behavior wrt automatic chip detection.
In case external testing environment is used (not from the tt-llk docker image), venv wasn't automatically sourced.
This issue with chip detection should be resolved now. Logic was misplaced.
venv sourcing issue caused some confusion, because it wasn't mentioned in the testing readme file. This is also addressed.
> fix: detect chip architecture automatically

- .github/workflows/on-pr.yml
- .github/workflows/pre-commit.yml
None
After we moved to GH Enterprise, our comment posting job started failing in all pull requests.
This change elevates permissions of workflows running on PRs to write, so it should fix our problem with comment posting job. It should now be able to write comments on PRs.
> ci: add pull request write permissions to workflows

- tt_llk_blackhole/common/inc/cunpack_common.h
- tt_llk_wormhole_b0/common/inc/cunpack_common.h
Currently denormals get flushed for int32 by unpack (unless explicitly disabled).  For uniformly random 32-bit test values this results in a spurious zero in 0.39% of cases (with a higher percentage of course for tests that only check small values).
This affects the upcoming support for int32 permute, which uses MOVD2B/MOVB2D and will have flushed denormals if it's not disabled.
Disable flush denormals for int32, similar to what is already done for uint16.
> Disable unpacker flush denormals for int32.

- .github/workflows/on-pr.yml
- tests/Makefile
- tests/helpers/include/data_format_inference.h
- tests/python_tests/helpers/test_config.py
None
A large portion of the test execution time was actually spent on build time. We were building ELF files inefficiently, and there was room for improvement by parallelizing the make process. This should have significant impact on the amount of time we spend on running the tests.
We now run make in parallel using 6 cores instead of building sequentially on a single core. I chose this number after testing locally to measure the improvement. The tests were performed on a machine with 12 cores, but using all available cores actually resulted in slower builds compared to using half of them. After several tests with different core counts, I found that 6 cores consistently gave the best results, achieving around a 3x speed improvement.
> fix: speed up test build times

- tests/python_tests/test_reduce.py
- tests/sources/reduce_test.cpp
- tt_llk_wormhole_b0/llk_lib/llk_math_reduce.h
#234 
Reduce test was failing for any pool type and row dimension
Changed golden generation for reduce row op to match one from tt-metal
> Fixed reduce row test

- .github/workflows/community-issue-tagging.yml
None
After move to GitHub Enterprise, we started seeing failures in this workflow, due to missing permissions.
Explicitly added permissions for PRs and issues.
> ci: fix permission issues for community-issue-tagging [skip ci]

- tt_llk_wormhole_b0/llk_lib/llk_pack_untilize.h
[#11573](https://github.com/tenstorrent/tt-metal/issues/11573)
Untilize operation can be performed either using the slow algorithm (unpack_untilize) or by using the fast algorithm (pack_untilize). However, pack_untilize had the limitation of input tensor fitting only in one Destination register bank (8 tiles width). The goal of this fix is to enable the pack_untilize operation to work for any input size, by fixing the block_ct_dim != full_ct_dim code path, where block_ct_dim is the number of tiles in the single Destination register bank, and full_ct_dim is the width of the whole input expressed in tiles.
The new address mode was added to avoid the constant clearing of y-counter, resulting in the rows of the input tensor being processed correctly.
> Fix pack_untilize for block_ct_dim != full_ct_dim

- tests/sources/eltwise_unary_sfpu_test.cpp
#262 
It was observed that cosine tests fail in isolation when run without reset between
Returned to using old cosine implementation from `tt-llk/tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_trigonometry.h`
> Returning to old cosine implementation

- tt_llk_blackhole/common/inc/ckernel.h
NA
In working on TT_REPLAY changes, I notice this asm wasn't the best
* the option push/pop does nothing
* Explicitly constructing constants in the asm forces clobbers and requires us to rematerialize a value.
* Remove the option push/pop
* making the '1<<18' and '1<<1' inputs means the compiler can now choose as to whether to use 2 regs (and no rematerialization), or a single reg and do a rematerialization.
- [YES] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [YES] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
> Improve gathering asms

- CODEOWNERS
None
So far, we haven't had clearly defined ownership in this repository. With the increased number of pull requests, it is taking us longer to process them, and some people with relevant knowledge might not be involved in the review process, leading to potential regressions in behavior. This is a problem with our review process that we might be able to address by defining code ownership. GitHub offers a tool in the form of the CODEOWNERS plugin, which is an industry standard these days and is already widely used throughout Tenstorrent in other repositories.
Using a CODEOWNERS file in a repository offers several advantages:
- The right people review the right parts of the code.
- No PRs fall through the cracks.
- Gatekeepers must review critical code sections, not just anyone.
- Helps …
> ci: create CODEOWNERS file and distribute ownership between LLK reviewers

- tests/python_tests/test_matmul.py
- tests/python_tests/test_matmul_pack_untilize.py
https://github.com/tenstorrent/tt-llk/issues/140
Enabled Matmul testing for format `Bfp8_b`, except for `test_matmul_unpack_tilize.py` since unpack_tilize doesn't work on block formats.
Now all tests run with format combinations including Bfp8_b, where the data format inference model infers all formats for kernels. By calling tests with ```test_formats = input_output_formats(supported_formats)``` this triggers use of data format inference model to determine the rest of the formats needed to support input and output formats in L1. 
Needed to change python test files because they leverage torch to generate tensors and torch doesn't recognize Bfp8_b so this needs to be worked around -- this work around is done throughout the entire test infra.
> [test Infra] Adding Bfp8_b to matmul tests

- .github/workflows/run-metal-tests-on-label.yml
None
If test infra label is set, new commits don't cancel the old runs, they just pile up.
Implemented cancellation of run in progress when new run is scheduled
> ci: cancel ongoing integration tests after a new commit

- tt_llk_wormhole_b0/common/inc/cunpack_common.h
- tt_llk_wormhole_b0/llk_lib/llk_math_transpose_dest.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_A.h
tenstorrent/tt-metal#21270
This is a slightly more efficient way to do transpose_wh_tile, by doing the middle face swap via unpack_A, which leaves only the within_face_transpose parts remaining.
- Add support for transpose_of_faces for 32-bit inputs to unpack_A (previously this was ignored).
- Add new transpose_of_faces template parameter to transpose_dest LLK API.  Important: this is currently ignored for non-32-bit data.
> Add 32-bit support for transpose_of_faces to A2D datacopy.

- tests/helpers/include/params.h
- tests/python_tests/helpers/format_arg_mapping.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_sfpu_binary.py
- tests/sources/sfpu_binary_test.cpp
- tt_llk_blackhole/llk_lib/llk_math_eltwise_binary_sfpu.h
- tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_binary_sfpu.h
#100 
Before this we had sfpu binary tests skipped since cpp test was not functional. 
Corrected cpp test implementation and supported parametrization through test infra. Also had to add includes to LLK code since some of sfpu binary code existed only in tt-metal
> Enabled sfpu binary tests inside of test infra

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_exp.h
- tt_llk_blackhole/instructions/assembly.yaml
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_exp.h
- tt_llk_wormhole_b0/instructions/assembly.yaml
https://github.com/tenstorrent/tt-metal/issues/17954
SDPA can take advantage of a few exp optimizations that did not have support.
- fused `exp(x*scalar)` in fast-approx mode
- large positive check skip in approx mode
In approx and non-approx mode, I changed the scalar value (passed as a runtime parameter) to be loaded as bfloat16 to work smoothly with how tt-metal kernels would expect to pass a scalar.
In approx mode, optionally skip the large-positive input check. The user can set this template arg when they know the range of their input makes this check unnecessary.
In fast-approx mode, the user can pass a `scale` value as a template arg, fp32 represented as uint32_t. This is applied to the constants of the algorithm to get `exp(x*scalar)` for free.
Background on fast-approx exp: …
> exp optimizations for SDPA

- tt_llk_blackhole/common/inc/ckernel.h
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_topk.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_topk.h
- tt_llk_wormhole_b0/llk_lib/llk_math_matmul.h
- tt_llk_wormhole_b0/llk_lib/llk_pack_untilize.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_AB_matmul.h
https://github.com/tenstorrent/tt-metal/issues/22101
In preparing to use a new intrinsics for instruction record & replay I noticed a whole slew of TT_REPLAY uses. It seems these can be TTI_REPLAY, which encodes as a static instruction, rather than an injected dynamic instruction. (I.e. at the point of code emission, there has been sufficient inlining to make all operands constants)
Replace TT_REPLAY with TTI_REPLAY
- [YES] New feature (non-breaking change which adds functionality)
- [YES ] [All post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/all-post-commit-workflows.yaml) CI passes
- [YES] [Blackhole Post commit](https://github.com/tenstorrent/tt-metal/actions/workflows/blackhole-post-commit.yaml) CI passes (if applicable)
> TT_REPLAY -> TTI_REPLAY

- tests/python_tests/helpers/test_config.py
- tests/python_tests/test_multiple_tiles_eltwise.py
#300 
Some tests are running fidelity sweep for operations not affected by math fidelity
Skipped those tests
> Skipping tests that are not elwmul and sweep fidelity

- tests/python_tests/helpers/unpack.py
- tt_llk_blackhole/llk_lib/llk_math_transpose_dest.h
- tt_llk_blackhole/llk_lib/llk_unpack_A.h
#134
`_llk_math_transpose_dest_` doesn't work for 32-bit types, e.g. Int32. 
Copy the 32-bit support added for Wormhole to Blackhole, including the support for 32-bit `transpose_of_faces` for `unpack_A`.
> Copy 32-bit _llk_math_transpose_dest_ implementation to Blackhole.

- tests/Makefile
https://github.com/tenstorrent/tt-llk/issues/331
The problem was raised by perf team, and I was already well into Makefile restructuring so I bundled it all together.
Namely, now it will be possible to recompile both test cases per core and main per core.
Makefile is restructured for easier maintenance and understanding. Also, we now force compilation of mains and tests for every core.
> build: restructure Makefile

- tests/Makefile
- tests/helpers/src/trisc.cpp
- tests/python_tests/helpers/profiler.py
#331 
This PR adds a generic zone for measuring test infra KERNEL execution time, as well as forcing the recompilation of `trisc.cpp` to make sure the `KERNEL_PROFILER:...:KERNEL` message is emitted to `stderr` every time a test is built.
> Add profiler zone for measuring kernel runtime

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_exp.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_exp.h
Closes #340
Insufficient macro config reset results in hang when using exp with fast_and_approx mode.
Reset macro config to the default during exp init.
> exp_init: reset LoadMacroConfig[Lane].Misc for all lanes.

- tests/helpers/src/brisc.cpp
#333 
Sfpi generated code wasn't able to get inside of v_if because value in LREG11 wasn't -1 as it expected it to be.
Changed brsic.cpp file to load -1 into register using TI_SFPCONFIG with modifier 1.
> Fixing sfpi expected LREG11 value of -1

- .github/workflows/sort-issues.yml
At the moment, our deployment goes to tt-llk root page on docs.tenstorrent.com. We'd like to "hide" these reports a bit deeper.
Page gets deployed to docs.tenstorrent.com/tt-llk/reports now.
> chore: change path of the deployed page

- tests/python_tests/test_profiler_overhead.py
- tests/sources/profiler_overhead_test.cpp
`profiler_overhead_test.py` tests how much overhead is added by putting a zone around code. It seems to sometimes fail on first iteration. My guess is that it performs inconsistently because the code is not in icache during the first iteration.
Ignore the result from the first iteration because it's inconsistent. All the other iterations should be OK because the first iteration will pull the code into cache.
> Fixup `profiler_overhead_test.py`

- tests/sources/sfpu_binary_test.cpp
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_shift.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_shift.h
https://github.com/tenstorrent/tt-metal/issues/22866
instruction modifier support not added for binary shift ops
Add ins mod support
> Add instr_mod support for binary shift

- tests/sources/sfpu_binary_test.cpp
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_shift.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_shift.h
None
We've observed breaking changes in tt-metal after https://github.com/tenstorrent/tt-llk/pull/365 got merged. See https://github.com/tenstorrent/tt-metal/actions/runs/15742340900/job/44371023416 for more information. Since there is currently no tt-metal counterpart to this change, we decided to revert it to unblock further tt-llk uplifts, since we have high priority tasks to finish that are currently stuck. Once tt-metal changes are prepared, this change can be reverted again.
FYI @Aswinmcw 
This reverts commit 7086a6941d9ede62c414d9d184121a54db569819.
> fix: revert "Add instr_mod support for binary shift (#365)"

- tests/helpers/include/perf.h
- tests/python_tests/helpers/perf.py
- tests/python_tests/perf_eltwise_binary_fpu.py
- tests/sources/eltwise_binary_fpu_perf.cpp
#327 
- Add `_perf_unpack_loop_set_valid`
- Use `^` to isolate math performance in `perf_eltwise_binary_fpu`
> perf: isolate math performance

- .gitignore
- tests/setup_clangd.sh
Currently, IDEs have a hard time indexing LLK code becaue they don't have information about:
- Include directories 
- Defines
Added a `tests/setup_clangd.sh` that does the following:
- Generates sensible `compile_flags.txt` based on provided architecture 
- Restarts `clangd` to force it to reload the file
This will allow all IDEs that can parse `compile_flags.txt` to index the codebase, and will work by default in all IDEs that rely on `clangd` for hints.
> tooling 🧑‍💻: add script to generate compile_flags.txt

- .github/workflows/on-pr.yml
None
This far we had to label perf-related PRs manually.
From now on, perf-related changes will be labelled automatically.
> ci: properly label performance-related PRs

- tests/Makefile
- tests/helpers/include/profiler.h
- tests/helpers/ld/sections.ld
- tests/python_tests/helpers/perf.py
- tests/python_tests/helpers/profiler.py
- tests/python_tests/helpers/test_config.py
- tests/python_tests/test_profiler_overhead.py
- tests/python_tests/test_profiler_primitives.py
The metadata that is needed for the profiler to properly function is currently passed compile time from `gcc` to the python infra using `#pragma message`. The `stderr` stream is then parsed on the python side for this metadata. This has already caused issues when files containing profiler primitives are not recompiled every run, because the message wouldn't get written to `stderr` 
This refactor changes how profiler metadata is passed to python infra. The profiler metadata will get pushed into the `.profiler_meta` section, which will get parsed after linking is done. Because meta is kept in the intermediate `.o` files, we have a guarantee that all metadata will end up in the final `.elf` of the corresponding thread.
> profiler ⌛: refactor how metadata is passed

- tt_llk_blackhole/llk_lib/llk_pack_untilize.h
https://github.com/tenstorrent/tt-metal/issues/24095
The static check in `pack_untilze` which checks if `row_num_datums < FACE_C_DIM` should be there, but it makes yolov4 and tranpose metal tests assert on BH because they pass `narrow_row = true` whenever they see a row < 32 datums, not < 16. When `transpose_wh_rm.cpp` is fixed so that it passes correctly these two parameters, we observe a PCC error on both BH and WH_B0. 
I am for now removing the static assert to unblock BH CI.
> "Revert" pack_untilize static assert for yolov4

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_comp.h
- tt_llk_blackhole/llk_lib/llk_math_eltwise_binary_sfpu_params.h
- tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_binary_sfpu_params.h
https://github.com/tenstorrent/tt-metal/issues/24216
binary sfpu params header not available in LLK
Add respective headers
> Add binary sfpu params to LLK

- CODEOWNERS
Add new code owners for testing infrastructure. Stefan and Strahinja are working on perf testing, it only makes sense to make them owners of this code.
Added Stefan and Strahinja as code owners.
> ci: add Strahinja and Stefan as tests' code owners

- tests/helpers/src/trisc.cpp
- tests/python_tests/conftest.py
- tests/python_tests/helpers/device.py
Write to the mailbox that the TRISC kernel is running immediately after detecting that tensix is complete, instead of doing it in trisc.cpp
When running multiple tests one after the other on simulator, only the first one passes, and the following ones fail. This is because at the end of the first test there is a 1 written to the mailbox. This value gets read, instead of the 2 which is supposed to be written into the mailbox by trisc.cpp. This results in the second test getting interpreted as already finished, when it has not even started yet. 
Instead of trisc.cpp writing the 2 into the mailbox, it is now done inside of device.py, right after detecting that Tensix operations are complete. 
- [x ] Bug fix (non-breaking change which fixes an issue)
> Relocate the TRISC kernel running write to mailbox

- .github/workflows/setup-and-test.yml
None
We disabled harbor last week in #416 due to service being down, to unblock our development. Since harbor is back in service, we should restore this setting, as it speeds up execution of our jobs.
Use `harbor.ci.tenstorrent.net` to fetch docker images.
> ci: use harbor for faster fetching of Docker images

- tests/python_tests/test_sfpu_binary.py
- tests/sources/sfpu_binary_test.cpp
#235 
SFPU binary test works only on single tile input
Modified mostly cpp test code to support reading, calculating and then writing multiple tiles back to L1
> Enable sfpu binary multiple tiles

- tests/python_tests/conftest.py
- tests/python_tests/helpers/config.py
- tests/python_tests/helpers/device.py
- tests/python_tests/helpers/target_config.py
Enable LLK tests to be ran on VCS simulator.
Add command line options for running the simulator and defining the simulator server port. Using these flags, adjust the test configuration: run the server, do not use arc_msg, calculate backoff and timeout differently when the simulator is used.
> Support running tests on simulator

- tests/Makefile
- tests/python_tests/conftest.py
- tests/python_tests/helpers/device.py
- tests/python_tests/helpers/profiler.py
This PR is supposed to fix two issues:
- Improve the solution in https://github.com/tenstorrent/tt-llk/pull/473
- The previous Makefile would handle `.d` files incorrectly, leading to errors and redundant rebuilds @lpremovicTT 
- `build` and `hw_specific` are now split into two subfolders for Wormhole and Blackhole files
- All intermediate files in the build process now get their own subfolders instead of getting mixed together
- Adds make variable `archname` to provide a way to override what arch you're building for
> test infra :test_tube:: decouple build from chip architecture

- tests/helpers/include/params.h
- tests/python_tests/helpers/format_arg_mapping.py
- tests/python_tests/helpers/test_config.py
- tests/sources/eltwise_unary_sfpu_test.cpp
- tests/sources/matmul_and_unary_sfpu_test.cpp
- tests/sources/reduce_test.cpp
None
This aims to simplify how we pass defines, especially for SFPU and other math operations.
This code change leans more towards autogeneration than cumbersome manual handling of #ifdefs
> refactor: change the way we add new sfpu types for testing

- tests/firmware/riscv/common/fw_debug.h
- tt_llk_blackhole/common/inc/ckernel.h
- tt_llk_blackhole/common/inc/ckernel_template.h
- tt_llk_blackhole/common/inc/cmath_common.h
- tt_llk_blackhole/llk_lib/llk_math_eltwise_binary.h
- tt_llk_blackhole/llk_lib/llk_math_eltwise_unary_datacopy.h
- tt_llk_blackhole/llk_lib/llk_pack_common.h
- tt_llk_blackhole/llk_lib/llk_unpack_common.h
- tt_llk_wormhole_b0/common/inc/ckernel.h
- tt_llk_wormhole_b0/common/inc/ckernel_template.h
- tt_llk_wormhole_b0/common/inc/cmath_common.h
- tt_llk_wormhole_b0/common/inc/cpack_common.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_dropout.h
- tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_binary.h
- tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_unary_datacopy.h
- tt_llk_wormhole_b0/llk_lib/llk_pack_common.h
- tt_llk_wormhole_b0/llk_lib/llk_unpack_common.h
I'm working on an effort to add an assert implementation to LLK. In the past there was FWASSERT but that hasn't been used for ~2 years. This PR is removes FWASSERT and FWLOG. Once I implement the new assert I will check which of these asserts are still valid, and which are stale/incorrect and add them again.
> test infra :test_tube:: remove fw_debug.h

- tests/python_tests/test_matmul_and_unary_sfpu.py
None
Adding more sfpu unary ops to fused matmul test.
Added more ops.
> fix: add more sfpu unary ops to mm fused test

- tests/helpers/include/ckernel_helper.h
- tests/helpers/ld/memory.blackhole.ld
- tests/helpers/ld/memory.wormhole.ld
- tt_llk_blackhole/common/inc/ckernel.h
- tt_llk_wormhole_b0/common/inc/ckernel.h
NA
`ckernel::instrn_buffer` is a pointer.  It is more efficient to declare it as an array and have the linker script provide the symbol. (although the compiler doesn't yet take full advantage of that, but future updates will).
This change requires care, as the (non-test) linker scripts are provided by tt-metal, and we can't rely on that and tt_llk being updated atomically.  This change has been tested both with and without the tt-metal change.  In the without case `instrn_buffer` remains a pointer.
We have temporary shim code here and in tt-metal, to allow asynchronous updating.  Once both are updated and tt-metal updates it's tt_llk submodule, this shim code can be removed (asynchronously).
- [Yes] New feature (non-breaking change which adds functionality)
- [YES ] [All post …
> Make instrn_buffer an array

- .github/workflows/check-stale.yml
None
We have some stale PRs that we'd like to automatically label as stale. This workflow has been added some time ago, but after moving to GH enterprise, it stopped working as expected since it was missing permissions.
- Added missing permissions to the check-stale workflow.
- Increased number of days before issue becomes stale to 700, since I wasn't sure about the number already in place (100 days)
> ci: fix permissions of check-stale workflow

- .github/workflows/setup-and-test.yml
None
Harbor service is down, disabling it for now. We use harbor as a cache server for docker images, it's an internal instance.
See an example of failed run: https://github.com/tenstorrent/tt-llk/actions/runs/16414826585/job/46378256374?pr=512
Harbor has been disabled.
> ci: disable harbor as it seems to be down

- .gitignore
- setup_clangd.sh
- tests/python_tests/conftest.py
- tests/setup_testing_env.sh
None
To streamline setting up testing environment, we move header download from python to shell script.
- Removed `download_headers()` pytest fixture from `conftest.py`
- Replaced this logic with a shell script embedded in `setup_testing_env.sh`
- `setup_clangd.sh` now sources `setup_testing_env.sh` so it becomes really easy to set up clangd in one step
> fix: move required header download to shell script

- tests/sources/ttnn_where_test.cpp
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_where.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_where.h
None
ITERATIONS parameter was not passed down to LLK
it is now passed
> passing ITERATIONS to where LLK

- tests/python_tests/helpers/perf.py
Mailboxes aren't reset correctly for first of the performance runs
> perf :zap:: reset_mailboxes in wrong place

- tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_binary.h
[](https://github.com/tenstorrent/tt-metal/issues/25577)
Eltwise MUL bcast COLs was missing an `if` statement for WH which was causing it to call ZEROACCs which could corrupt the output data in Dest.
-> `if constexpr (binary_reuse_dest != EltwiseBinaryReuseDestType::NONE)`
This issue was actually fixed prior for BH, but never back-ported to WHB0.
Added the omitted check.
> Fix eltwise MUL bcast COLs from calling ZEROACC with no Dest reuse

- tests/sources/eltwise_unary_sfpu_test.cpp
- tests/sources/matmul_and_unary_sfpu_test.cpp
Fix incorrect template parameters in calls to `_calculate_sqrt_`.
> Fix sqrt tests.

- .github/workflows/mirror-fork-branches.yml
- .github/workflows/sort-issues.yml
None
This workflow creates a mirror image of a fork branch. That will be useful for running metal integration tests (post commit tests), and should help us spend less time juggling the branches.
Added a new workflow for creating mirror images of branches coming from forks.
> ci: mirror fork branch workflow

- .github/workflows/trigger-tt-metal-post-commit.yml
None
I was hoping to merge https://github.com/tenstorrent/tt-metal/pull/26180 by the time this merges, but that hasn't happened due to different reasons, leaving this (llk) workflow in a broken state.
This is just a band-aid solution, until the other PR is merged.
Changed metal post-commit workflow to trigger metal workflow from a branch, not main.
> ci: temp enable metal workflow from a branch

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_typecast.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_typecast.h
https://github.com/tenstorrent/tt-metal/issues/25656
-1 is represented as -1.00781 after int->fp16b typecast
This is because we are storing the output back as fp16b (mode 2) which only overwrites the Hi16 bits of the fp32 dest reg. Then when the packer packs out the value, it will round it again (including Lo16 bits) resulting in double rounding.
- Change the STORE mode of typecast kernels to 0 (default) in order to overwrite all 32bits of Dest. This fixes the issue.
- Also update stoch_rnd instruction to use imm operand for descale - this has no effect anyways but may prevent LREG3 from being used down the line by accident.
> Fix typecast fp16_b double rounding

- .github/scripts/install-exalens.sh
- .github/scripts/install-smi.sh
- .github/workflows/build-images.yml
- .github/workflows/on-pr.yml
- .github/workflows/pre-commit.yml
None
This PR aims at replacing `pip install git+<repo>` of `tt-smi` with wheel-based installation for improved reliability and performance. This was made possible with completion of https://github.com/tenstorrent/tt-smi/issues/99
Key benefits:
- Pre-compiled wheels eliminate compilation time
- Consistent binaries across environments
- No build tools required in runtime containers
- Explicit wheel versions for reproducible builds
- Updated install scripts to use configurable wheel URLs
- Added version-based tag extraction for dynamic URL construction
> ci: install tt-smi from prebuilt wheel instead of installing it from git repository

- .github/workflows/on-pr.yml
None
Assume there are 3 PRs --- PR1, PR2 and PR3, and there is a workflow to run to get the required checks. When all PRs queued in the merge queue, 3 workflows started.
workflow 1 running on main + PR1
workflow 2 running on main + PR1 + PR2
workflow 3 running on main + PR1 + PR2 + PR3
Now, if we want to move PR3 to be at the head of the queue, 3 new workflows will start:
workflow 4 running on main + PR3
workflow 5 running on main + PR3 + PR1
workflow 6 running on main + PR3 + PR1 + PR2
When this happens, workflow 1, 2 and 3 should be cancelled automatically because the results are irrelevant at this point.
However, currently this is not done automatically.
Added checks to prevent running orphaned builds.
> ci: terminate obsolete merge group runs

- tests/sources/reduce_test.cpp
- tt_llk_blackhole/llk_lib/llk_math_reduce.h
- tt_llk_wormhole_b0/llk_lib/llk_math_reduce.h
https://github.com/tenstorrent/tt-metal/issues/25266
Setting Tf32 as ALU FORMAT for SrcA changes behaviour of MOVB2D/D2B. This arises in situations where the values in SrcA (being reduced) are Tf32.
This only affects WH, BH works correctly for Tf32 as well.
Set to valid format in the reduce init, since expecting OP writers to know this HW quirk seems unreasonable.
This must be accompanied by tt-metal change as well. (https://github.com/tenstorrent/tt-metal/pull/26528)
> Change ALU_FORMAT of SrcA in reduce init to fix MOVB2D bug with Tf32

- tests/helpers/include/params.h
- tests/python_tests/helpers/device.py
- tests/python_tests/helpers/dimensions.py
- tests/python_tests/helpers/format_config.py
- tests/python_tests/helpers/golden_generators.py
- tests/python_tests/helpers/param_config.py
- tests/python_tests/helpers/stimuli_generator.py
- tests/python_tests/helpers/test_config.py
- tests/python_tests/perf_fast_tilize.py
- tests/python_tests/test_eltwise_unary_datacopy.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/python_tests/test_fast_tilize.py
- tests/python_tests/test_math_matmul.py
- tests/python_tests/test_matmul.py
- tests/python_tests/test_matmul_and_unary_sfpu.py
- tests/python_tests/test_matmul_pack_untilize.py
- tests/python_tests/test_matmul_unpack_tilize.py
- tests/python_tests/test_multiple_tiles_eltwise.py
- tests/python_tests/test_pack_untilize.py
- tests/python_tests/test_reduce.py
- tests/python_tests/test_sfpu_binary.py
- tests/python_tests/test_tilize_calculate_untilize_L1.py
- tests/python_tests/test_unpack_matmul.py
- tests/python_tests/test_unpack_tilize.py
- tests/python_tests/test_unpack_untilize.py
- tests/sources/matmul_test.cpp
https://github.com/tenstorrent/tt-llk/issues/562
This closes the gap in the previous implementation, which only handled a hardcoded case (2×2 tiles), and now enables full coverage of all 58 valid combinations under the following constraints:
* When using 32-bit dest registers: output matrix must have ≤ 4 tiles.
* When using 16-bit dest registers: output matrix may use up to 8 tiles.
Test coverage jumped from 72 to 2088 test cases
This PR extends the matmul testing infrastructure to fully support writes to memory with multiple tiles across various matrix dimensions. Key changes include:
✅ Differentiated writes to memory when inputA and inputB have different numbers of tiles and matrix dimensions.
✅ Generalized test infrastructure to accept dynamic tile dimensions and input configurations. …
> Support dynamic multiple tiles  + matmul sweep over all matrix dimension combinations 

- .github/workflows/nightly.yml
None
Nightly run did not start due to missing permissions for packages. This caused failure on fetching docker images, which is a prerequisite for further workflow steps.
Added missing permissions.
> [skip ci] chore: add missing permissions to nightly runs

- tests/python_tests/helpers/format_arg_mapping.py
- tests/python_tests/helpers/golden_generators.py
- tests/python_tests/test_eltwise_unary_sfpu.py
- tests/sources/eltwise_unary_sfpu_test.cpp
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_relu.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_relu.h
https://github.com/tenstorrent/tt-metal/issues/26719
int32 support not provided for relu variants
Provide int32 support
```math
\text{ReLU}_{\text{min}}(x, L) = \max(x, L)
```
```math
\text{ReLU}_{\text{max}}(x, U) = \max\big(0, \min(x, U)\big)
```
> Extend relu impl to int support

- tt_llk_wormhole_b0/llk_lib/llk_unpack_tilize.h
(https://github.com/tenstorrent/tt-metal/issues/22298)
Unpack Tilize to Dest, in wormhole uses only one context and the register THCON_SEC0_REG3_Base_address_ADDR32 is used for addressing. We potentially run the mop twice while changing the register inbetween using MMIO. We cannot make an MMIO wait for the unpacker to finish using stallwaits, leading to race conditions. More in the issue. 
Used REG2FLOP since we can make UNPACKER wait till REG2FLOP is finished, and if there is a STALLWAIT waiting on unpacker before it with a corresponding instruction, that instruction will be blocked till unpacker is not finished thus blocking the REG2FLOP too, which is the case here.
> Fix race between MMIO and Unpacker

- tests/python_tests/helpers/perf.py
Variance is hard to intuitively reason about, stddev seems more appropriate here
> perf :zap:: use stddev instead of variance

- tt_llk_blackhole/common/inc/ckernel_sfpu.h
- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_max_pool_indices.h
- tt_llk_wormhole_b0/common/inc/ckernel_sfpu.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_max_pool_indices.h
https://github.com/tenstorrent/tt-metal/issues/17202
Maxpool op that also return the index of the max value is needed. Topk local sort can accomplish this, but also performs a lot of extra work (sorting whole tile column) while here we only need to extract single max value.
Wrote implementation for max reduce with indices for 9 row tiles. This is the specific case that is needed to meet perf requirement for a customer.
Other cases/more general implementation can be added as needed, and based on this one (just needs to be expanded).
- no tests in tt-llk yet, tested on tt-metal branch which will be merged with a test
> Create max pool with indices LLK on SFPU

- tests/python_tests/helpers/perf.py
- tests/python_tests/helpers/test_config.py
- tests/python_tests/perf_fast_tilize.py
- tests/sources/fast_tilize_test.cpp
Introduces `loop_factor` as test configuration setting. This is supposed to be used as a setting with `ProfilerBuild.Yes` and can be used to minimize the overhead of a profiler zone for short zones by running it multiple times.
> perf :zap:: introduce loop_factor as profiler feature

- tt_llk_wormhole_b0/llk_lib/llk_pack.h
[#28380](https://github.com/tenstorrent/tt-metal/issues/28380)
Fast tilize wasn't tested and doesnt support BFP4/2 output dataformats.
Added special cases in packer tile size calculation for output formats with less than 8 bits per datum.
> Add BFP4/2 support for fast_tilize

- tests/helpers/include/data_format_inference.h
- tests/helpers/include/perf.h
- tests/python_tests/helpers/test_config.py
- tests/python_tests/perf_pack_untilize.py
- tests/sources/math_transpose_perf.cpp
- tests/sources/pack_untilize_perf.cpp
#432 
Adds new performance benchmark for _llk_pack_untilize_
Supports 3 modes:
- L1 to L1
- Pack isolate
- L1 Congested
> perf :zap:: benchmark _llk_pack_untilize_

- .github/workflows/nightly-perf-tests.yml
None
Workflow execution failed due to insufficient permissions - the caller has a narrower permission scope than required by the callee.
Added missing permissions
> [skip ci] ci: fix missing permissions for performance nightly workflow

- .github/workflows/trigger-tt-metal-post-commit.yml
None
This PR fixes an issue where post-commit workflow status messages were overwriting each other by adding unique message identifiers. The workflow was previously writing test results to the same message box, making messages "sticky" and only showing the latest results.
- Added unique message-id parameter using GitHub's run_id to prevent message overwriting
- Ensures each workflow run creates a separate status message for better tracking
> [skip ci] ci: stop overwriting messages with post-commit workflow results

- tests/sfpi-version.sh
None
SFPI update that doesn’t check ARCH_foo macros in sfpi header file, that interferes with Quasar development, which is using BH as a base.
New SFPI version 7.2.0
> [skip ci] build: update sfpi to 7.2.0

- .github/workflows/nightly.yml
- .github/workflows/run-perf-tests.yml
- .github/workflows/setup-and-test.yml
None
This PR makes the test timeout configurable in GitHub Actions workflows to address [timing out](https://github.com/tenstorrent/tt-llk/actions/runs/18053155525) nightly tests caused by new matmul tests. Instead of hardcoding the timeout value, it introduces a configurable parameter that allows different workflows to specify appropriate timeout values.
- Added a `timeout_minutes` input parameter to the `setup-and-test` workflow with a default of 80 minutes
- Updated `performance` test workflows to use 120-minute timeouts
- Set `nightly` test workflows to use 240-minute timeouts for longer-running tests
> [skip ci] ci: make test timeout configurable

- tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_rounding_ops.h
- tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_rounding_ops.h
Link to Github Issue https://github.com/tenstorrent/tt-metal/issues/29506
Floor and trunc returns int max limit for nan and inf.
Updated floor and trunc to return inf and nan
> Add inf and nan handling in rounding ops

- tt_llk_blackhole/common/inc/cpack_common.h
- tt_llk_blackhole/llk_lib/llk_pack.h
https://github.com/tenstorrent/tt-metal/issues/27504?reload=1?reload=1?reload=1%3Freload%3D1?reload=1%3Freload%3D1%3Freload%3D1%3Freload%3D1
Problem description
Some OPs call hardware configure with artificial values of numfaces / partial tile /face_r_dim. From what I understand it is related to sharding. So when the packer reconfiguring function is called the registers which were affected by the specific call to hardware initialization may not be modified, leading to packer behaving not as expected.
What's changed
Reinitialized the config registers which are affected by num_faces, partial_tile and face_r_dim. This increases some performance cost which could be reduced if we had some form of tracking mechanism (which is outside the scope of this PR). Unlike PR …
> Fix packer reconfig to account for num_faces and partial_face

- .github/workflows/on-pr.yml
- .github/workflows/run-perf-tests.yml
- .github/workflows/setup-and-test.yml
- tests/python_tests/perf_math_transpose.py
None
Perf tests haven't been running so far, except during nightly runs. That opened a space for regressions if the perf files are touched without checking. This makes that step mandatory.
- Introduce 2 performance test steps (for BH and WH) and tied them to changes in performance files
- Added additional test split group to accommodate for the increased number of tests
> [skip ci] ci: run performance tests if perf files are touched

- tests/setup_testing_env.sh
None
tt-llk relies on several headers from tt-metal. These get downloaded prior to running tests.
These headers have been moved in https://github.com/tenstorrent/tt-metal/pull/29908, and we've started observing failures.
This PR fixes the url path of the required headers.
> [skip ci] build: correct url path for metal headers
