tests/firmware/riscv/blackhole/l1_address_map.h
tests/firmware/riscv/wormhole/l1_address_map.h
tests/helpers/include/ckernel_helper.h
tests/helpers/include/params.h
tests/helpers/src/brisc.cpp
tests/helpers/src/trisc.cpp
tests/python_tests/helpers/device.py
tests/python_tests/helpers/pack.py
tests/python_tests/helpers/stimuli_generator.py
tests/python_tests/helpers/test_config.py
tests/python_tests/helpers/unpack.py
tests/python_tests/helpers/utils.py
tests/setup_env.sh
tests/sources/eltwise_unary_datacopy_test.cpp
tests/sources/eltwise_unary_sfpu_test.cpp
tests/sources/fill_dest_test.cpp
tests/sources/matmul_test.cpp
tests/sources/multiple_tiles_eltwise_test.cpp
tests/sources/pack_untilize_test.cpp
tests/sources/reduce_test.cpp
tests/sources/sfpu_binary_test.cpp
tests/sources/tilize_calculate_untilize_L1.cpp
tests/sources/unpack_tilize_test.cpp
tests/sources/unpack_untilize_test.cpp
tt_llk_blackhole/common/inc/ckernel_defs.h
tt_llk_wormhole_b0/common/inc/ckernel_defs.h

Description TBD.
Mostly small improvements and avoiding preprocessor as much as possible.

chore: refactor test infra

---

tt_llk_blackhole/llk_lib/llk_pack_untilize.h

The issue was that the narrow row feature did not exist on the BH board.
These additions modify the LLK to accept narrow_row as a parameter and change the algorithm to use 1 packer interface if the data arrives in a narrow row manner (narrow row relies on only having Face 0 and Face 2 in the tile, so we have to skip the Face 1/Face 3 reads).
The modifications were tested with the expected input and provide the same output as the WH_B0.

Added narrow Row LLK support

---

tests/python_tests/conftest.py
tests/python_tests/helpers/param_config.py
tests/python_tests/pytest.ini
tests/python_tests/test_tilize_calculate_untilize_L1.py
tests/setup_env.sh
tests/sources/multiple_tiles_eltwise_test.cpp

**Visual Progress + Concise Test Summary**
Upgraded the look and readability of test output using `pytest-sugar`. Here we ca track which test cases pass, skip or fail and on the side we have an active overview of how our tests are progressing i.e what percentage of tests have completed. At the end we get a clear and concise overview of all the tests we ran and their result summary. 
**Simplified Command-Line Invocation + Increased Verbosity**
The test configuration has been automated via the `pytest.ini` file. This eliminates the need to manually add flags (like `-v`) each time tests are run. The `-v` verbosity flag is set up by default in the `pytest.ini` file, ensuring that test parameters are clearly displayed in the output, making it easier to track the setup, state and condition of …

[Test Infrastructure] Upgraded Test Interface and Output of Results

---

CONTRIBUTING.md
README.md
tests/README.md

None
Adding documentation on TT Bounty program, similar to tt-forge and tt-metal.
Adding information about TT Bounty program

docs: update markdown files

---

tt_llk_blackhole/common/inc/cpack_common.h

https://github.com/tenstorrent/tt-metal/issues/18779#issuecomment-2782834310
Matmul hangs non deterministically on P100 scrappy boards but not production boards. This PR fixes the issue of packer thread updating the register containing an address used by the packer before the packer mop finishes. The change added a wait to the packer in an existing STALLWAIT and a NOP after a WRCFG (without which another race condition may be there). I tested the code without the added nop to make sure timing was the same as the code without this PR, and I found the issue to be resolved wheras the original code hanged. This proves the presence of the race condition, and moreover when the test passed in debug mode I saw PCC values near 0 which also shows garbage values got written as output by the packer. …

Remove race conditions in packer thread.

---

tests/setup_external_testing_env.sh

Update setup_external_testing_env.sh to remove unused URL

---

tt_llk_wormhole_b0/llk_lib/llk_unpack_tilize.h

tenstorrent/tt-metal#20409
Allows these APIs to be tested with LLK test infra.
Moved functions from tt-metal (tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_unpack_tilize_api.h) to tt-llk.
Will need to coordinate removal on tt-metal side.

Move llk_unpack_tilizeA_B_* from tt-metal to tt-llk.

---

.github/workflows/on-pr.yml

ci: enable merge queue builds

---

tests/python_tests/test_matmul_pack_untilize.py
tests/sources/matmul_pack_untilize_test.cpp

https://github.com/orgs/tenstorrent/projects/123?pane=issue&itemId=109135763&issue=tenstorrent%7Ctt-llk%7C161
Increasing Matmul test coverage. Wrote a test to cover matmul fusion with  pack_untilize.

[Test Infra] Added Test to Combine Matmul with Packing Untilize

---

tt_llk_blackhole/common/inc/ckernel_sfpu.h
tt_llk_wormhole_b0/common/inc/ckernel_sfpu.h

fix: add missing sfpu_converter.h include

---

.github/workflows/on-pr.yml

ci: checkout code before checking for diffs

---

.github/workflows/on-pr.yml

ci: execute workflow on merge to main

---

.github/workflows/community-issue-tagging.yml

fix community-issue-tagging.yml

---

.github/.dockerignore
.github/Dockerfile.base
.github/Dockerfile.ird
.github/scripts/install-smi.sh
tests/python_tests/conftest.py
tests/requirements.txt

build: don't use pip cache when installing tt-smi inside Docker image

---

.github/workflows/check-stale.yml

ci: check against stale PRs and issues

---

.github/workflows/sort-issues.yml

Script path was wrong.
Fixed path for calling

ci: correct calling path

---

tests/python_tests/helpers/param_config.py
tests/python_tests/test_tilize_calculate_untilize_L1.py

User should run all tests using input-output parametrization in order to utilize data format inference model. This is very useful because all input-output format combinations are supported by the data format inference model. If we hard code the combinations we might make a mistake as some hard-coded combinations with certain flags such as dest_Acc are not supported on certain architecture, and the data format inference model takes care of this in order to support all input-output combinations and increase coverage.
Fused tests that incorporate 2 or more llk pipeline runs currently don't utilize data format inference model because all the formats are the same (in order to reuse output of first call as input to second llk pipeline run ...) 
However if all formats are the same this isn't …

Activating Data Format Inference model with Input Output format parametrization Flexibility for same formats 

---

tt_llk_blackhole/llk_lib/llk_unpack_tilize.h

tenstorrent/tt-metal#22618
Move llk_unpack_tilizeA_B_* from tt-metal to tt-llk, Blackhole edition.
Added:
- `_llk_unpack_tilizeA_B_mop_config_`
- `_llk_unpack_tilizeA_B_init_`
- `_llk_unpack_tilizeA_B_`

Move llk_unpack_tilizeA_B_* from tt-metal to tt-llk, Blackhole edition.

---

tests/firmware/riscv/common/llk_sfpu_types.h
tests/helpers/include/params.h
tests/python_tests/helpers/format_arg_mapping.py
tests/python_tests/test_eltwise_unary_sfpu.py
tests/sources/eltwise_unary_sfpu_test.cpp
tt_llk_blackhole/common/inc/ckernel_defs.h
tt_llk_blackhole/common/inc/ckernel_sfpu.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_activations.h
tt_llk_wormhole_b0/common/inc/ckernel_defs.h
tt_llk_wormhole_b0/common/inc/ckernel_sfpu.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_activations.h

https://github.com/tenstorrent/tt-metal/issues/22786
celu impl missing in LLK
Add celu implementation along with LLK testing

feat: Add celu impl with tests

---

tests/requirements.txt

None
Using latest available versions
Versions of torch, numpy and others have been hldated
| Package        | Old Version | New Version |
|----------------|-------------|-------------|
| numpy  | 2.2.5   | 2.2.6    |
| pytest   | 8.3.5   | 8.4.0    |
| torch    | 2.7.0    | 2.7.1     |

chore: update testing requirements

---

tests/sources/eltwise_unary_sfpu_test.cpp

NA
iteration count mismatched
Update iteration count to 32

Update celu testing iterations

---

tests/README.md

NA
external environment setup needs to be sourced, bash will run in subshell and wont activate new env in current shell
Tell devs to source the script
Beautify the remaining Readme
Preview : 
https://github.com/tenstorrent/tt-llk/tree/Aswinmcw/external_deps_docs/tests#readme

docs: Beautify test infra docs

---

.github/workflows/run-metal-tests-on-label.yml
.github/workflows/tt-metal-integration-tests.yml

ci: switch integration tests to run on the new blackhole runners

---

README.md

None
[Deepwiki](https://deepwiki.com/tenstorrent/tt-llk) is already indexing our repository, but adding the badge will make it index it regularly. It generates nice documentation and combines the code, and has integrated AI bot who can answer questions for you. Could be useful for some new developers. tt-metal is already using it, and it seems quite nice in their case.
New badge is added to the README.

docs: add link to deepwiki

---

tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_trigonometry.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_trigonometry.h

Link to Github Issue https://github.com/tenstorrent/tt-metal/issues/23168
Acosh has been implemented as a composite operation.
Added llk support for acosh

Add acosh implementation

---

tests/helpers/include/params.h
tests/python_tests/helpers/format_arg_mapping.py
tests/python_tests/helpers/golden_generators.py
tests/python_tests/test_sfpu_binary.py
tests/sources/sfpu_binary_test.cpp
tt_llk_blackhole/common/inc/ckernel_defs.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_binary.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_shift.h
tt_llk_wormhole_b0/common/inc/ckernel_defs.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_binary.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_shift.h

N/A
binary ops testing added only for float
Adds int dataformat for testing with some improvements

test: Binary int32 testing

---

tests/python_tests/helpers/perf.py
tests/python_tests/perf_eltwise_binary_fpu.py
tests/sources/eltwise_binary_fpu_perf.cpp

#327 
- Add pack performance isolation

test :test_tube:: isolate pack performance

---

tests/sources/sfpu_binary_test.cpp
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_shift.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_shift.h

Reverts tenstorrent/tt-llk#385
Metal pipelines passed in https://github.com/tenstorrent/tt-metal/pull/23522

Revert "fix: revert "Add instr_mod support for binary shift (#365)""

---

tests/helpers/include/profiler.h
tests/python_tests/helpers/perf.py
tests/python_tests/helpers/test_config.py
tests/python_tests/helpers/utils.py
tests/python_tests/test_eltwise_unary_datacopy.py
tests/python_tests/test_eltwise_unary_sfpu.py
tests/python_tests/test_matmul.py
tests/python_tests/test_matmul_and_unary_sfpu.py
tests/python_tests/test_matmul_pack_untilize.py
tests/python_tests/test_matmul_unpack_tilize.py
tests/python_tests/test_multiple_tiles_eltwise.py
tests/python_tests/test_pack_untilize.py
tests/python_tests/test_profiler_overhead.py
tests/python_tests/test_profiler_primitives.py
tests/python_tests/test_reduce.py
tests/python_tests/test_sfpu_binary.py
tests/python_tests/test_tilize_calculate_untilize_L1.py
tests/python_tests/test_unpack_tilize.py
tests/python_tests/test_unpack_untilize.py

#334 , depends on #404  
Unifies the test building and running process for profiler and non-profiler build. Also removes code duplication by grouping calls into a function

test infra :test_tube:: unify test running

---

.github/workflows/setup-and-test.yml

Remove harbor from container path since its down

---

.gitignore
tests/python_tests/helpers/perf.py
tests/python_tests/perf_eltwise_binary_fpu.py
tests/requirements.txt

In a future PR the code
Generate a Scatter graph for the performance benchmark

perf :zap:: generate baseline scatter graph

---

tests/helpers/include/params.h
tests/python_tests/helpers/format_arg_mapping.py
tests/python_tests/helpers/golden_generators.py
tests/python_tests/test_sfpu_binary.py
tests/sources/sfpu_binary_test.cpp
tt_llk_blackhole/common/inc/ckernel_defs.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_activations.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_shift.h
tt_llk_wormhole_b0/common/inc/ckernel_defs.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_activations.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_shift.h

https://github.com/tenstorrent/tt-metal/issues/22862
logical shift ops missing in LLK
Add logical right shift op along with tests

feat: Add logical right shift op

---

tt_llk_blackhole/llk_lib/llk_math_eltwise_unary_sfpu_params.h
tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_unary_sfpu_params.h

https://github.com/tenstorrent/tt-metal/issues/24279
unary sfpu params defined in metal repo
migrate it to llk repo

Add unary sfpu params

---

tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_log.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_sqrt.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_trigonometry.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_log.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_sqrt.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_trigonometry.h

Link to Github Issue https://github.com/tenstorrent/tt-metal/issues/23171
Problem description
atanh has been implemented as a composite operation.
What's changed
Added llk support for atanh

Add atanh implementation

---

tests/python_tests/conftest.py

None
Tests were failing with very strange errors when a user used a shared directory between runners.
Scenario:
1. Check out repo on weka and use, e.g., a blackhole machine
2. Run tests (BH architecture-specific files are downloaded as a prerequisite before running tests)
3. Acquire a WH machine and run tests
4. 💥 all tests fail with very strange compile errors
We had a bug in our logic because we were only checking for the presence of the hw_specific/inc directory when running tests, but we weren't checking if the architecture matches. That worked so far because we were only using `/localdev` for development. @vkrsmanovicTT stumbled upon this error because he used a weka shared directory.
A change was implemented to actually keep track of the architecture for which the hardware-specific …

fix: check architecture before downloading headers

---

tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_silu.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_silu.h

Link to Github Issue https://github.com/tenstorrent/tt-metal/issues/24758 https://github.com/tenstorrent/tt-metal/issues/24787
Increased device kernel execution time for SiLU after migration.
Update silu op
shape used: [1,1,8192, 8192]

Update silu op 

---

tests/helpers/include/params.h
tests/python_tests/helpers/format_arg_mapping.py
tests/python_tests/helpers/golden_generators.py
tests/python_tests/test_eltwise_unary_sfpu.py
tests/sources/eltwise_unary_sfpu_test.cpp
tt_llk_blackhole/common/inc/ckernel_sfpu.h
tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_fill.h
tt_llk_wormhole_b0/common/inc/ckernel_sfpu.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_fill.h

https://github.com/tenstorrent/tt-metal/issues/24610
fill operator needs int32 support
Adds fill implementation

feat: Add fill implementation

---

CONTRIBUTING.md
infra/check_copyright_config.yaml
tests/Makefile
tests/firmware/riscv/wormhole/l1_address_map.h
tests/python_tests/helpers/utils.py
tests/python_tests/test_matmul_and_unary_sfpu.py
tests/python_tests/test_matmul_unpack_tilize.py
tt_llk_blackhole/common/inc/ckernel.h
tt_llk_blackhole/common/inc/ckernel_addrmod.h
tt_llk_blackhole/common/inc/ckernel_debug.h
tt_llk_blackhole/common/inc/ckernel_structs.h
tt_llk_blackhole/llk_lib/llk_math_common.h
tt_llk_wormhole_b0/common/inc/ckernel.h
tt_llk_wormhole_b0/common/inc/ckernel_addrmod.h
tt_llk_wormhole_b0/common/inc/ckernel_debug.h
tt_llk_wormhole_b0/common/inc/ckernel_structs.h
tt_llk_wormhole_b0/llk_lib/llk_math_common.h

These are all typos in comments or docs, with the exception of `infra/check_copyright_config.yaml` where there was a typo in the ignore check: `tt_llk_blackhole/hw_speific/` -> `tt_llk_blackhole/hw_specific/`.

Fix various minor typos.

---

.github/workflows/setup-and-test.yml

Reverts tenstorrent/tt-llk#518
Harbor is back online

Revert "ci: disable harbor as it seems to be down"

---

tests/python_tests/conftest.py
tests/python_tests/helpers/param_config.py
tests/python_tests/perf_eltwise_binary_fpu.py
tests/python_tests/pytest.ini
tests/python_tests/test_eltwise_unary_datacopy.py
tests/python_tests/test_eltwise_unary_sfpu.py
tests/python_tests/test_fast_tilize.py
tests/python_tests/test_matmul.py
tests/python_tests/test_matmul_and_unary_sfpu.py
tests/python_tests/test_matmul_pack_untilize.py
tests/python_tests/test_matmul_unpack_tilize.py
tests/python_tests/test_multiple_tiles_eltwise.py
tests/python_tests/test_pack_untilize.py
tests/python_tests/test_reduce.py
tests/python_tests/test_sfpu_binary.py
tests/python_tests/test_tilize_calculate_untilize_L1.py
tests/python_tests/test_ttnn_where.py
tests/python_tests/test_unpack_tilize.py
tests/python_tests/test_unpack_untilize.py

This PR refactors `param_config` to make it easier to add new parameters for sweep, and also makes it a bit easier to write tests,

test infra 🧪: refactor parametrization

---

tests/python_tests/test_ttnn_where.py
tt_llk_blackhole/llk_lib/llk_math_eltwise_ternary_sfpu.h
tt_llk_blackhole/llk_lib/llk_math_eltwise_ternary_sfpu_params.h
tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_ternary_sfpu.h
tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_ternary_sfpu_params.h

#527 
Some of issues that were left in comment of #520 need to be addressed.
Most of tasks from #527 are done. Only thing left is to allow random dest offsets of condition, true and false tiles.

Cleanup ternary API for ttnn where

---

tt_llk_blackhole/common/inc/sfpu/ckernel_sfpu_activations.h
tt_llk_wormhole_b0/common/inc/sfpu/ckernel_sfpu_activations.h

https://github.com/tenstorrent/tt-metal/issues/22786
During celu migration in metal, we found that scalar needs to be bitcasted to handle the inf/nan cases
get the params as uint and use converter to store it in vFloat

fix: Update celu implementation

---

tt_llk_blackhole/common/inc/ckernel_sfpu.h
tt_llk_blackhole/llk_lib/llk_math_eltwise_ternary_sfpu_params.h
tt_llk_wormhole_b0/llk_lib/llk_math_eltwise_ternary_sfpu_params.h

NA
header missed for BH
Adds and update header

Add missing header in BH for where op

---

CONTRIBUTING.md
README.md
tests/requirements.txt
tests/setup_testing_env.sh

NA
Some users forgot to setup pre commit hook and it reflects once they opened a PR
Added pre-commit hook as a setup during env setup

feat: Add auto pre-commit installation feature

---

tests/python_tests/helpers/format_arg_mapping.py
tests/python_tests/helpers/golden_generators.py
tests/python_tests/helpers/test_config.py
tests/python_tests/test_math_matmul.py
tests/sources/math_matmul_test.cpp

https://github.com/orgs/tenstorrent/projects/123?pane=issue&itemId=118348523&issue=tenstorrent%7Ctt-llk%7C453
Sweeping parameters for math_matmul API. Sweeping `throttle level` and `transpose`.
Tests coverage increased from 72 to  864 cases.

[Test Infra] math matmul API: sweep for transpose/haloize + throttle mode

---

.github/workflows/trigger-tt-metal-post-commit.yml

None
Fixing some things…
Updated version of the workflow.

ci: update metal post commit tests workflow

---

.github/workflows/trigger-tt-metal-post-commit.yml

None
Update visual style of message containing post-commit results.
Visual style and icons have been updated.

ci: improve post-commit workflow result message

---

tests/python_tests/helpers/format_arg_mapping.py
tests/python_tests/helpers/golden_generators.py
tests/python_tests/helpers/test_config.py
tests/python_tests/helpers/utils.py
tests/python_tests/test_unpack_matmul.py
tests/sources/unpack_matmul_test.cpp

https://github.com/orgs/tenstorrent/projects/123?pane=issue&itemId=118367435&issue=tenstorrent%7Ctt-llk%7C465
Sweeping parameters for unpack_AB_matmul API. Currently sweeping stochastic rounding and transpose. 
Tests coverage increased from 72 to 576 cases.

[Test Infra] unpack AB matmul API sweep (first round)

---

.github/workflows/on-pr.yml

None
This reverts commit 61fa793e6e375f9e0c7a68dce0de520f52e35147.
Reverted #572

fix: revert "ci: terminate obsolete merge group runs (#572)"

---

.github/workflows/manual-tt-metal-integration.yml
.github/workflows/on-pr.yml
.github/workflows/run-metal-tests-on-label.yml

None
Use new GitHub runners, because old ones will be decomissioned in two weeks.
New GitHub runner labels

ci: use new GitHub runners

---

.github/workflows/nightly.yml
.github/workflows/on-pr.yml
.github/workflows/setup-and-test.yml
.github/workflows/sort-issues.yml
tests/python_tests/pytest.ini

None
Add a workflow for running nightly tests.
New workflow has been added to support running nightly tests.
New pytest mark has been added for nightly tests.

feat: introduce nightly test run workflow

---

.github/workflows/trigger-tt-metal-post-commit.yml

ci: use PAT for triggering workflows from the other repository (tt-metal)

---

tests/python_tests/conftest.py
tests/python_tests/helpers/perf.py
tests/python_tests/perf_eltwise_binary_fpu.py
tests/python_tests/perf_fast_tilize.py
tests/python_tests/perf_math_transpose.py
tests/python_tests/perf_unpack_tilize.py
tests/python_tests/perf_unpack_transpose.py

Move reporting fixture into perf.py

---

tt_llk_blackhole/llk_lib/llk_pack_untilize.h
tt_llk_wormhole_b0/llk_lib/llk_pack_untilize.h

Wanted to check if this will break something in tt-metal

pack_untilize: assert full_ct_dim % block_ct_dim == 0

---

.github/Dockerfile.base
.github/Dockerfile.ird.slim
.github/workflows/run-perf-tests.yml
.github/workflows/setup-and-test.yml

None
Nightly perf runs are running ok but failing to check the mandatory step. So if some tests were to fail, that wouldn’t cause the entire run to fail due to disabled check.
Enabled final check for test passing/failing.

[skip ci] ci: publish performance data as part of perf test runs

---

tests/python_tests/perf_math_transpose.py
tests/sources/math_transpose_perf.cpp

Improved the `perf_math_transpose` performance benchmark. Unfortunately now it consistently hangs.
I cannot seem to find a reason for this test to hang, so I think it's just that now it consistently hits one of the bugs in `perf_math_transpose`

perf :zap:: improved perf_math_transpose

---

tests/python_tests/perf_pack_untilize.py

We turned it off because it caused issues in CI. I currently cannot replicate the issue locally.

[skip ci] perf :zap:: enable _llk_pack_untilize benchmark for blackhole

---

tests/python_tests/perf_matmul.py
tests/sources/matmul_perf.cpp

L1 to L1 performance benchmark for matmul
More Isolated benchmarks will come in the near future.

perf :zap:: matmul performance benchmark

---

.github/scripts/install-exalens.sh
tests/setup_external_testing_env.sh

None
Update to the latest exalens, which includes the latest UMD changes required for ttsim.
New version of exalens.

ci: update tt-exalens version
